import { Component } from './Component';
export { createElement } from './core/createElement';
export { defineCustomElement as tag } from './core/defineCustomElement';
export { getContext } from './util/getContext';
export { useHook } from './util/useHook';
export { Component } from './Component';
export { Element } from './Element';
export { Fragment } from './Fragment';
export { Hook } from './Hook';
export declare const Context: typeof Component.Context;
export declare type Context = Component.Context;
export declare const Portal: typeof Component.Portal;
export declare type Portal = Component.Portal;
